### ISSUE TITLE
✨개발환경을 Tuist로 구현

### ISSUE THREAD

**Issue by kimscastle** [AllenSwiftClass/LottoDiary#15]
## 💬 Description
기존에 하나의 xcode.proj로 프로젝트를 진행했을때의 문제점이 발견되어서 이를 방지하기위한 Tuist를 적용할 예정입니다

## 📝 Todo
- [ ] Tuist레포지토리를 하나 파서 Tuist프로젝트를 생성
- [ ] 기존에 brody와 sunny가 만든 파일들 옮기기
- [ ] 폴더생성할때 템플릿적용해서 폴더트리구조 통일시키기
